var seeing_the_world = ['Brazil', 'Australia', 'USA', 'Canada', 'Dubai'];
console.log(seeing_the_world);
seeing_the_world.sort();
console.log(seeing_the_world);
seeing_the_world.reverse();
console.log(seeing_the_world);
seeing_the_world.reverse();
console.log(seeing_the_world);
seeing_the_world.sort();
console.log(seeing_the_world);
